version: 1
default_environment: dev
project_id: meltano-b849cd48-8429-42dd-9ee2-1240ff73438f
plugins:
  utilities:
    - name: dagster
      namespace: dagster
      pip_url: -e /workspace dbt-postgres
      executable: dagster_invoker
      settings:
        - name: dagster_home
          env: DAGSTER_HOME
          value: $MELTANO_PROJECT_ROOT/.meltano
          label: The home folder of Dagster
        - name: repository_dir
          env: REPOSITORY_DIR
          value: $MELTANO_PROJECT_ROOT/orchestrate
          label: The root folder of the dagster project
      commands:
        initialize:
          args: initialize
          executable: dagster_extension
        init:
          args: initialize
          executable: dagster_extension
        up:
          args: -f $REPOSITORY_DIR/repository.py
          executable: dagit_invoker
      config:
        repository_dir: $MELTANO_PROJECT_ROOT/orchestrate
jobs:
  - name: job-with-schedule
    tasks:
      - tap-csv target-jsonl
  - name: job-without-schedule
    tasks:
      - tap-csv target-postgres
      - tap-csv target-snowflake

schedules:
  - name: schedule
    interval: "@daily"

    job: job-with-schedule

environments:
  - name: dev
  - name: staging
  - name: prod
