version: 1
default_environment: dev
project_id: meltano-b849cd48-8429-42dd-9ee2-1240ff73438f
plugins:
  extractors:
    - name: tap-csv
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
      config:
        files:
          - entity: sample_one
            path: /workspace/project/extract/sample.csv
            keys: [id]
          - entity: sample_two
            path: /workspace/project/extract/sample.csv
            keys: [id]

  loaders:
    - name: target-postgres
      variant: transferwise
      pip_url: pipelinewise-target-postgres
      config:
        dbname: postgres
        user: postgres
        password: postgres
        host: postgres

  transformers:
    - name: dbt-postgres
      variant: dbt-labs
      pip_url: dbt-core~=1.2.0 dbt-postgres~=1.2.0
      env:
        DBT_POSTGRES_HOST: postgres
        DBT_POSTGRES_USER: postgres
        DBT_POSTGRES_PORT: "5432"
        DBT_POSTGRES_DBNAME: postgres
        DBT_POSTGRES_PASSWORD: postgres
        DBT_POSTGRES_SCHEMA: warehouse

  utilities:
    - name: dagster
      namespace: dagster
      pip_url: -e /workspace
      executable: dagster_invoker
      settings:
        - name: dagster_home
          env: DAGSTER_HOME
          value: $MELTANO_PROJECT_ROOT/.meltano/dagster
          label: The home folder of Dagster
        - name: repository_dir
          env: REPOSITORY_DIR
          value: $MELTANO_PROJECT_ROOT/orchestrate/dagster
          label: The root folder of the Dagster project
        - name: cloud_organization
          env: DAGSTER_CLOUD_ORGANIZATION
          label: The Dagster Cloud organization you would like to deploy to.
        - name: cloud_api_token
          env: DAGSTER_CLOUD_API_TOKEN
          kind: password
          label: The api token of your Dagster Cloud environment.
        - name: cloud_deployment
          env: DAGSTER_CLOUD_DEPLOYMENT
          value: prod
          label: The default deployment to deploy to.
        - name: cloud_location_name
          env: DAGSTER_CLOUD_LOCATION_NAME
          value: meltano
          label: The name of the Cloud Deployment location.
      commands:
        initialize:
          args: initialize
          executable: dagster_extension
        init:
          args: initialize
          executable: dagster_extension
        start:
          args: -f $REPOSITORY_DIR/repository.py
          executable: dagit_invoker
        describe:
          args: describe
          description: Describe the Dagster Extension.
          executable: dagster_extension
        deploy:
          args: |
            serverless 
            deploy 
            -f orchestrate/dagster/repository.py 
            --location-name $DAGSTER_CLOUD_LOCATION_NAME 
            --base-image=prebuild 
            $MELTANO_PROJECT_ROOT
          executable: cloud_invoker
      env:
        DBT_POSTGRES_HOST: postgres
        DBT_POSTGRES_USER: postgres
        DBT_POSTGRES_PORT: "5432"
        DBT_POSTGRES_DBNAME: postgres
        DBT_POSTGRES_PASSWORD: postgres
        DBT_POSTGRES_SCHEMA: warehouse
        DAGSTER_CLOUD_ORGANIZATION: quantile

      config:
        repository_dir: $MELTANO_PROJECT_ROOT/orchestrate/dagster
        cloud_organization: quantile
        cloud_location_name: meltano
jobs:
  - name: ingestion
    tasks:
      - tap-csv target-postgres
      - tap-csv target-postgres
      - dbt-postgres:build
      - dbt-postgres:test
  - name: tap-target
    tasks:
      - tap-csv target-postgres
  - name: help
    tasks:
      - meltano --help

schedules:
  - name: schedule
    interval: "@daily"
    job: tap-target

environments:
  - name: dev
  - name: staging
  - name: prod
