services:
  vscode:
    build:
      context: .
      dockerfile: vscode.Dockerfile
    tty: true
    volumes:
      - .env:/root/.env
      - ..:/workspace:cached
      - pip-cache:/root/.cache/pip
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/com.docker.cli:/usr/bin/com.docker.cli
    environment:
      MELTANO_PROJECT_ROOT: /workspace/project

  # postgres:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #     PGDATA: /data/postgres
  #   volumes:
  #     - postgres:/data/postgres
  #   ports:
  #     - 5432:5432

volumes:
  postgres:
  pip-cache:
