services:
  vscode:
    build:
      context: .
      dockerfile: vscode.Dockerfile
    tty: true
    volumes:
      - ..:/workspace:cached
      - pip-cache:/root/.cache/pip
    environment:
      MELTANO_PROJECT_ROOT: /workspace/meltano
    env_file:
      - .env

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
  pip-cache:
